// Data for Sai Baba Pradakshina
const saiBabaMantraText = "<div class='sai-mantra-border'><span class='sai-line-1'>Om Sai Namo Namah</span> <br> <span class='sai-line-2'>Shri Sai Namo Namah</span> <br> <span class='sai-line-3'>Jai Jai Sai Namo Namah</span> <br> <span class='sai-line-4'>Sadguru Sai Namo Namah</span></div>";
const saiBabaMantra = Array(108).fill(saiBabaMantraText);

const saiBabaMantraTextTelugu = "<div class='sai-mantra-border'><span class='sai-line-1'>ఓం సాయై నమో నమః</span> <br> <span class='sai-line-2'>శ్రీ సాయి నమో నమః</span> <br> <span class='sai-line-3'>జై జై సాయి నమో నమః</span> <br> <span class='sai-line-4'>సద్గురు సాయి నమో నమః</span></div>";
const saiBabaMantraTelugu = Array(108).fill(saiBabaMantraTextTelugu);

// Data for Sarana Ghosha and Naama Japam
const saranaGhosha = [
    "ōṃ śrī svāminē śaraṇamayyappa",
    "om hari hara sutanē śaraṇamayyappa",
    "om āpadbhāndavanē śaraṇamayyappa",
    "om anādharakṣakanē śaraṇamayyappa",
    "om akhilāṇḍa kōṭi brahmāṇḍanāyakanē śaraṇamayyappa",
    "om annadāna prabhuvē śaraṇamayyappa",
    "om ayyappanē śaraṇamayyappa",
    "om ariyāṅgāvu ayyāvē śaraṇamayyappa",
    "om ārchan kōvil aranē śaraṇamayyappa",
    "om kuḻattapulai bālakanē śaraṇamayyappa",
    "om erumēli śāstanē śaraṇamayyappa",
    "om [vāvarusvāminē śaraṇamayyappa]",
    "om kannimūla mahā gaṇapatiyē śaraṇamayyappa",
    "om nāgarājavē śaraṇamayyappa",
    "om mālikāpuratta dulōkadēvi śaraṇamayyappa mātāyē",
    "om kuruppa svāmiyē śaraṇamayyappa",
    "om sēvippa varkānanda mūrtiyē śaraṇamayyappa",
    "om kāśivāsiyē śaraṇamayyappa",
    "om haridvāra nivāsiyē śaraṇamayyappa",
    "om śrīraṅgapaṭṭaṇa vāsiyē śaraṇamayyappa",
    "om karuppatūr vāsiyē śaraṇamayyappa",
    "om gollapūḍi [dvārapūḍi] dharmaśāstāvē śaraṇamayyappa",
    "om sadguru nādhanē śaraṇamayyappa",
    "om viḻāli vīranē śaraṇamayyappa",
    "om vīramaṇikaṇṭanē śaraṇamayyappa",
    "om dharmaśāstravē śaraṇamayyappa",
    "om śaraṇugōṣapriyavē śaraṇamayyappa",
    "om kāntimalai vāsanē śaraṇamayyappa",
    "om ponnambalavāsiyē śaraṇamayyappa",
    "om pandaḻaśiśuvē śaraṇamayyappa",
    "om vāvarin tōḻanē śaraṇamayyappa",
    "om mōhinīsutavē śaraṇamayyappa",
    "om kankaṇḍa daivamē śaraṇamayyappa",
    "om kaliyugavaradanē śaraṇamayyappa",
    "om sarvarōga nivāraṇa dhanvantara mūrtiyē śaraṇamayyappa",
    "om mahiṣimardananē śaraṇamayyappa",
    "om pūrṇa puṣkaḻa nādhanē śaraṇamayyappa",
    "om van-puli vāhananē śaraṇamayyappa",
    "om baktavatsalanē śaraṇamayyappa",
    "om bhūlōkanādhanē śaraṇamayyappa",
    "om ayindumalaivāsavē śaraṇamayyappa",
    "om śabari girīśanē śaraṇamayyappa",
    "om irumuḍi priyanē śaraṇamayyappa",
    "om abhiṣēkapriyanē śaraṇamayyappa",
    "om vēdappōruḻīnē śaraṇamayyappa",
    "om nitya brahmachāriṇē śaraṇamayyappa",
    "om sarva maṅgaḻadāyakanē śaraṇamayyappa",
    "om vīrādhivīranē śaraṇamayyappa",
    "om ōṅkārappōruḻē śaraṇamayyappa",
    "om ānandarūpanē śaraṇamayyappa",
    "om bhakta chittādivāsanē śaraṇamayyappa",
    "om āśrita-vatsalanē śaraṇamayyappa",
    "om bhūta gaṇādipatayē śaraṇamayyappa",
    "om śakti-rūpanē śaraṇamayyappa",
    "om śāntamūrtayē śaraṇamayyappa",
    "om padunēlbābaḍikki adhipatiyē śaraṇamayyappa",
    "om uttam apuruṣānē śaraṇamayyappa",
    "om ṛṣikula rakṣakunē śaraṇamayyappa",
    "om vēdapriyanē śaraṇamayyappa",
    "om uttarānakṣatra jātakanē śaraṇamayyappa",
    "om tapōdhananē śaraṇamayyappa",
    "om yaṅgaḻa kuladaivamē śaraṇamayyappa",
    "om jaganmōhanē śaraṇamayyappa",
    "om mōhanarūpanē śaraṇamayyappa",
    "om mādhavasutanē śaraṇamayyappa",
    "om yadukulavīranē śaraṇamayyappa",
    "om māmalai vāsanē śaraṇamayyappa",
    "om ṣaṇmukha-sōdaranē śaraṇamayyappa",
    "om vēdāntarūpanē śaraṇamayyappa",
    "om śaṅkara sutanē śaraṇamayyappa",
    "om śatrusaṃhārinē śaraṇamayyappa",
    "om sadguṇamūrtayē śaraṇamayyappa",
    "om parāśaktiyē śaraṇamayyappa",
    "om parātparanē śaraṇamayyappa",
    "om parañjyōtiyē śaraṇamayyappa",
    "om hōmapriyanē śaraṇamayyappa",
    "om gaṇapati sōdaranē śaraṇamayyappa",
    "om dharma śāstrāvē śaraṇamayyappa",
    "om viṣṇusutanē śaraṇamayyappa",
    "om sakala-kaḻā vallabhanē śaraṇamayyappa",
    "om lōka rakṣakanē śaraṇamayyappa",
    "om amita-guṇākaranē śaraṇamayyappa",
    "om alaṅkāra priyanē śaraṇamayyappa",
    "om kannimārai-kappavanē śaraṇamayyappa",
    "om bhuvanēśvaranē śaraṇamayyappa",
    "om mātāpitā gurudaivamē śaraṇamayyappa",
    "om svāmiyin puṅgāvanamē śaraṇamayyappa",
    "om aḻudānadiyē śaraṇamayyappa",
    "om aḻudāmēḍē śaraṇamayyappa",
    "om kaḻliḍraṅkuṇḍrē śaraṇamayyappa",
    "om karimalai yēṭramē śaraṇamayyappa",
    "om karimalai yērakkamē śaraṇamayyappa",
    "om pēriyān vaṭṭamē śaraṇamayyappa",
    "om cheriyāna vaṭṭamē śaraṇamayyappa",
    "om pambānadiyē śaraṇamayyappa",
    "om pambayiḻ vīḻḻakkē śaraṇamayyappa",
    "om nīlimalai yēṭramē śaraṇamayyappa",
    "om appāchi mēḍē śaraṇamayyappa",
    "om śabaripīṭamē śaraṇamayyappa",
    "om śaraṃ gutti ālē śaraṇamayyappa",
    "om bhasmakuḻamē śaraṇamayyappa",
    "om padunēṭṭāṃ baḍiyē śaraṇamayyappa",
    "om neyyībhi ṣēkapriyanē śaraṇamayyappa",
    "om karpūra jyōtiyē śaraṇamayyappa",
    "om jyōtisvarūpanē śaraṇamayyappa",
    "om makara jyōtiyē śaraṇamayyappa",
    "om pandala rājakumāranē śaraṇamayyappa",
    "ōṃ harihara sutanē ānandachittan ayyappa svāminē śaraṇamayyappa"
];

const saranaGhoshaTelugu = [
    "ఓం శ్రీ స్వామినే శరణమయ్యప్ప",
    "ఓం హరి హర సుతనే శరణమయ్యప్ప",
    "ఓం ఆపద్భాందవనే శరణమయ్యప్ప",
    "ఓం అనాధరక్షకనే శరణమయ్యప్ప",
    "ఓం అఖిలాండ కోటి బ్రహ్మాండనాయకనే శరణమయ్యప్ప",
    "ఓం అన్నదాన ప్రభువే శరణమయ్యప్ప",
    "ఓం అయ్యప్పనే శరణమయ్యప్ప",
    "ఓం అరియాంగావు అయ్యావే శరణమయ్యప్ప",
    "ఓం ఆర్చన్ కోవిల్ అరనే శరణమయ్యప్ప",
    "ఓం కుళత్తపులై బాలకనే శరణమయ్యప్ప",
    "ఓం ఎరుమేలి శాస్తనే శరణమయ్యప్ప",
    "ఓం [వావరుస్వామినే శరణమయ్యప్ప]",
    "ఓం కన్నిమూల మహా గణపతియే శరణమయ్యప్ప",
    "ఓం నాగరాజవే శరణమయ్యప్ప",
    "ఓం మాలికాపురత్త దులోకదేవి శరణమయ్యప్ప మాతాయే",
    "ఓం కురుప్ప స్వామియే శరణమయ్యప్ప",
    "ఓం సేవిప్ప వర్కానంద మూర్తియే శరణమయ్యప్ప",
    "ఓం కాశివాసియే శరణమయ్యప్ప",
    "ఓం హరిద్వార నివాసియే శరణమయ్యప్ప",
    "ఓం శ్రీరంగపట్టణ వాసియే శరణమయ్యప్ప",
    "ఓం కరుప్పతూర్ వాసియే శరణమయ్యప్ప",
    "ఓం గొల్లపూడి [ద్వారపూడి] ధర్మశాస్తావే శరణమయ్యప్ప",
    "ఓం సద్గురు నాధనే శరణమయ్యప్ప",
    "ఓం విళాలి వీరనే శరణమయ్యప్ప",
    "ఓం వీరమణికంటనే శరణమయ్యప్ప",
    "ఓం ధర్మశాస్త్రవే శరణమయ్యప్ప",
    "ఓం శరణుగోషప్రియవే శరణమయ్యప్ప",
    "ఓం కాంతిమలై వాసనే శరణమయ్యప్ప",
    "ఓం పొన్నంబలవాసియే శరణమయ్యప్ప",
    "ఓం పందళశిశువే శరణమయ్యప్ప",
    "ఓం వావరిన్ తోళనే శరణమయ్యప్ప",
    "ఓం మోహినీసుతవే శరణమయ్యప్ప",
    "ఓం కన్కండ దైవమే శరణమయ్యప్ప",
    "ఓం కలియుగవరదనే శరణమయ్యప్ప",
    "ఓం సర్వరోగ నివారణ ధన్వంతర మూర్తియే శరణమయ్యప్ప",
    "ఓం మహిషిమర్దననే శరణమయ్యప్ప",
    "ఓం పూర్ణ పుష్కళ నాధనే శరణమయ్యప్ప",
    "ఓం వన్-పులి వాహననే శరణమయ్యప్ప",
    "ఓం బక్తవత్సలనే శరణమయ్యప్ప",
    "ఓం భూలోకనాధనే శరణమయ్యప్ప",
    "ఓం అయిందుమలైవాసవే శరణమయ్యప్ప",
    "ఓం శబరి గిరీశనే శరణమయ్యప్ప",
    "ఓం ఇరుముడి ప్రియనే శరణమయ్యప్ప",
    "ఓం అభిషేకప్రియనే శరణమయ్యప్ప",
    "ఓం వేదప్పోరుళీనే శరణమయ్యప్ప",
    "ఓం నిత్య బ్రహ్మచారిణే శరణమయ్యప్ప",
    "ఓం సర్వ మంగళదాయకనే శరణమయ్యప్ప",
    "ఓం వీరాధివీరనే శరణమయ్యప్ప",
    "ఓం ఓంకారప్పోరుళే శరణమయ్యప్ప",
    "ఓం ఆనందరూపనే శరణమయ్యప్ప",
    "ఓం భక్త చిత్తాదివాసనే శరణమయ్యప్ప",
    "ఓం ఆశ్రిత-వత్సలనే శరణమయ్యప్ప",
    "ఓం భూత గణాదిపతయే శరణమయ్యప్ప",
    "ఓం శక్తి-రూపనే శరణమయ్యప్ప",
    "ఓం శాంతమూర్తయే శరణమయ్యప్ప",
    "ఓం పదునేల్బాబడిక్కి అధిపతియే శరణమయ్యప్ప",
    "ఓం ఉత్తమపురుషానే శరణమయ్యప్ప",
    "ఓం ఋషికుల రక్షకునే శరణమయ్యప్ప",
    "ఓం వేదప్రియనే శరణమయ్యప్ప",
    "ఓం ఉత్తరానక్షత్ర జాతకనే శరణమయ్యప్ప",
    "ఓం తపోధననే శరణమయ్యప్ప",
    "ఓం యంగళ కులదైవమే శరణమయ్యప్ప",
    "ఓం జగన్మోహనే శరణమయ్యప్ప",
    "ఓం మోహనరూపనే శరణమయ్యప్ప",
    "ఓం మాధవసుతనే శరణమయ్యప్ప",
    "ఓం యదుకులవీరనే శరణమయ్యప్ప",
    "ఓం మామలై వాసనే శరణమయ్యప్ప",
    "ఓం షణ్ముఖ-సోదరనే శరణమయ్యప్ప",
    "ఓం వేదాంతరూపనే శరణమయ్యప్ప",
    "ఓం శంకర సుతనే శరణమయ్యప్ప",
    "ఓం శత్రుసంహారినే శరణమయ్యప్ప",
    "ఓం సద్గుణమూర్తయే శరణమయ్యప్ప",
    "ఓం పరాశక్తియే శరణమయ్యప్ప",
    "ఓం పరాత్పరనే శరణమయ్యప్ప",
    "ఓం పరంజ్యోతియే శరణమయ్యప్ప",
    "ఓం హోమప్రియనే శరణమయ్యప్ప",
    "ఓం గణపతి సోదరనే శరణమయ్యప్ప",
    "ఓం ధర్మ శాస్త్రావే శరణమయ్యప్ప",
    "ఓం విష్ణుసుతనే శరణమయ్యప్ప",
    "ఓం సకల-కళా వల్లభనే శరణమయ్యప్ప",
    "ఓం లోక రక్షకనే శరణమయ్యప్ప",
    "ఓం అమిత-గుణాకరనే శరణమయ్యప్ప",
    "ఓం అలంకార ప్రియనే శరణమయ్యప్ప",
    "ఓం కన్నిమారై-కప్పవనే శరణమయ్యప్ప",
    "ఓం భువనేశ్వరనే శరణమయ్యప్ప",
    "ఓం మాతాపితా గురుదైవమే శరణమయ్యప్ప",
    "ఓం స్వామియిన్ పుంగావనమే శరణమయ్యప్ప",
    "ఓం అళుదానదియే శరణమయ్యప్ప",
    "ఓం అళుదామేడే శరణమయ్యప్ప",
    "ఓం కళ్లిడ్రంకుండ్రే శరణమయ్యప్ప",
    "ఓం కరిమలై యేట్రమే శరణమయ్యప్ప",
    "ఓం కరిమలై యేరక్కమే శరణమయ్యప్ప",
    "ఓం పేరియాన్ వట్టమే శరణమయ్యప్ప",
    "ఓం చెరియాన వట్టమే శరణమయ్యప్ప",
    "ఓం పంబానదియే శరణమయ్యప్ప",
    "ఓం పంబయిళ్ వీళ్ళక్కే శరణమయ్యప్ప",
    "ఓం నీలిమలై యేట్రమే శరణమయ్యప్ప",
    "ఓం అప్పాచి మేడే శరణమయ్యప్ప",
    "ఓం శబరిపీటమే శరణమయ్యప్ప",
    "ఓం శరం గుత్తి ఆలే శరణమయ్యప్ప",
    "ఓం భస్మకుళమే శరణమయ్యప్ప",
    "ఓం పదునేట్టాం బడియే శరణమయ్యప్ప",
    "ఓం నెయ్యీభి షేకప్రియనే శరణమయ్యప్ప",
    "ఓం కర్పూర జ్యోతియే శరణమయ్యప్ప",
    "ఓం జ్యోతిస్వరూపనే శరణమయ్యప్ప",
    "ఓం మకర జ్యోతియే శరణమయ్యప్ప",
    "ఓం పందల రాజకుమారనే శరణమయ్యప్ప",
    "ఓం హరిహర సుతనే ఆనందచిత్తన్ అయ్యప్ప స్వామినే శరణమయ్యప్ప"
];

const naamaJapamEnglish = Array(108).fill("Om Sri Swamiye Saranam Ayyappa");
const naamaJapamTelugu = Array(108).fill("ఓం శ్రీ స్వామియే శరణం అయ్యప్ప");

const englishSlogans = [
    "svāmi śaraṇaṃ – ayyappa śaraṇaṃ",
    "bhagavān śaraṇaṃ – bhagavati śaraṇaṃ",
    "dēvan śaraṇaṃ – dēvī śaraṇaṃ",
    "dēvan pādaṃ – dēvī pādaṃ",
    "svāmi pādaṃ – ayyappa pādaṃ",
    "bhagavānē – bhagavatiyē",
    "īśvaranē – īśvariyē",
    "dēvanē – dēviyē",
    "śaktanē – śaktiyē",
    "svāmiyē – ayyapō",
    "pallikaṭṭu – śabarimalakku",
    "irumuḍikaṭṭu – śabarimalakku",
    "kattuṅkaṭṭu – śabarimalakku",
    "kallummulluṃ – kālikimettai",
    "ettiviḍayyā – tūkikkaviḍayyā",
    "dēhabalandā – pādabalandā",
    "yāraikāna – svāmiyaikāna",
    "svāmiyaikaṇḍāl – mōkṣaṅkiṭṭuṃ",
    "svāmimārē – ayyappamārē",
    "neyyābhiṣēkaṃ – svāmikkē",
    "karpūradīpaṃ – svāmikkē",
    "pālābhiṣēkaṃ – svāmikkē",
    "bhasmābhiṣēkaṃ – svāmikkē",
    "tēnābhiṣēkaṃ – svāmikkē",
    "chandanābhiṣēkaṃ – svāmikkē",
    "pūlābhiṣēkaṃ – svāmikkē",
    "pannīrābhiṣēkaṃ – svāmikkē",
    "pambāśisuvē – ayyappā",
    "kānanavāsā – ayyappā",
    "śabarigirīśā – ayyappā",
    "pandaḻarājā – ayyappā",
    "pambāvāsā – ayyappā",
    "van‍pulivāhana – ayyappā",
    "sundararūpā – ayyappā",
    "ṣaṇmugasōdara – ayyappā",
    "mōhinitanayā – ayyappā",
    "gaṇēśasōdara – ayyappā",
    "hariharatanayā – ayyappā",
    "anādharakṣaka – ayyappā",
    "sadgurunāthā – ayyappā",
    "svāmiyē – ayyappō",
    "ayyappō – svāmiyē",
    "svāmi śaraṇaṃ – ayyappa śaraṇaṃ"
];

const teluguSlogans = [
    "స్వామి శరణం – అయ్యప్ప శరణం",
    "భగవాన్ శరణం – భగవతి శరణం",
    "దేవన్ శరణం – దేవీ శరణం",
    "దేవన్ పాదం – దేవీ పాదం",
    "స్వామి పాదం – అయ్యప్ప పాదం",
    "భగవానే – భగవతియే",
    "ఈశ్వరనే – ఈశ్వరియే",
    "దేవనే – దేవియే",
    "శక్తనే – శక్తియే",
    "స్వామియే – అయ్యపో",
    "పల్లికట్టు – శబరిమలక్కు",
    "ఇరుముడికట్టు – శబరిమలక్కు",
    "కత్తుంకట్టు – శబరిమలక్కు",
    "కల్లుంముల్లుం – కాలికిమెత్తై",
    "ఎత్తివిడయ్యా – తూకిక్కవిడయ్యా",
    "దేహబలందా – పాదబలందా",
    "యారైకాన – స్వామియైకాన",
    "స్వామియైకండాల్ – మోక్షంకిట్టుం",
    "స్వామిమారే – అయ్యప్పమారే",
    "నెయ్యాభిషేకం – స్వామిక్కే",
    "కర్పూరదీపం – స్వామిక్కే",
    "పాలాభిషేకం – స్వామిక్కే",
    "భస్మాభిషేకం – స్వామిక్కే",
    "తేనాభిషేకం – స్వామిక్కే",
    "చందనాభిషేకం – స్వామిక్కే",
    "పూలాభిషేకం – స్వామిక్కే",
    "పన్నీరాభిషేకం – స్వామిక్కే",
    "పంబాశిసువే – అయ్యప్పా",
    "కాననవాసా – అయ్యప్పా",
    "శబరిగిరీశా – అయ్యప్పా",
    "పందళరాజా – అయ్యప్పా",
    "పంబావాసా – అయ్యప్పా",
    "వన్‍పులివాహన – అయ్యప్పా",
    "సుందరరూపా – అయ్యప్పా",
    "షణ్ముగసోదర – అయ్యప్పా",
    "మోహినితనయా – అయ్యప్పా",
    "గణేశసోదర – అయ్యప్పా",
    "హరిహరతనయా – అయ్యప్పా",
    "అనాధరక్షక – అయ్యప్పా",
    "సద్గురునాథా – అయ్యప్పా",
    "స్వామియే – అయ్యప్పో",
    "అయ్యప్పో – స్వామియే",
    "స్వామి శరణం – అయ్యప్ప శరణం"
];

const mantras = [
    {
        deity: 'Ganesh',
        image: 'images/ganesh.jpeg',
        mantraEnglish: 'Ekadantaaya Vidmahe\nVakratundaaya Dheemahi\nTanno Danti Prachodayaat',
        mantraTelugu: 'ఏకదంతాయ విద్మహే, వక్రతుండాయ ధీమహీ, తన్నో దంతి ప్రచోదయాత్',
        audio: 'audio/ganesh_mantra.mpeg'
    },
    {
        deity: 'Kartikeya',
        image: 'images/kartikeya.jpeg',
        mantraEnglish: 'Sharavana Bhavāya Vidmahē\nKārtikēyāya Dhīmahī\nTannō Skandaḥ Prachōdayāt',
        mantraTelugu: 'శరవణ భవాయ విద్మహే కార్తికేయాయ ధీమహి తన్నో స్కంద ప్రచోదయాత్',
        audio: 'audio/kartikeya_mantra.mpeg'
    },
    {
        deity: 'Hanuman',
        image: 'images/Hanuman.jpeg',
        mantraEnglish: 'Om Aim Hrīm Hanumate Śrī Rāmdūtāya Namaḥ',
        mantraTelugu: 'ఓం ఐమ్ హ్రీమ్ హనుమతే శ్రీ రామదూతాయ నమః',
        audio: 'audio/Hanuman_mantras.mpeg'
    },
    {
        deity: 'Ananta Shesha',
        image: 'images/Ananta Shesha.jpg',
        mantraEnglish: 'Om Sarparajaya Vidmahe Nagarajaya Dhimahi Tanno Anantah Prachodayat',
        mantraTelugu: 'ఓం సర్పరాజాయ విద్మహే నాగరాజాయ ధీమహి తన్నో అనంతః ప్రచోదయాత్',
        audio: 'audio/Ananta_Shesha_mantra.mpeg'
    },
    {
        deity: 'Durga Matha',
        image: 'images/Durga_matha_mantra.jpeg',
        mantraEnglish: 'Om Katyayanaya Vidmahe\nKanyakumari Dhimahi\nTanno Durgah Prachodayat',
        mantraTelugu: 'ఓం కాత్యాయనాయ విద్మహే కన్యాకుమారి ధీమహీ తన్నో దుర్గ: ప్రచోదయాత్',
        audio: 'audio/Durga_matha_mantra.mpeg'
    }
];
